[package]
name = "snowball"
version = "0.1.0"
edition = "2021"

[features]
png = ["tiny-skia"]
lottie = []

[dependencies]
tiny-skia = { version = "0.8", optional = true }
rand = "0.8"
hashbrown = "0.13"

[profile.release]
debug = 1
